
name: 'Export'
description: 'Converts an obsidian vault as GitHub Markdown in specified output directory'
inputs:
  vault-location:
    description: 'Path to root of Obsidian vault'
    required: true
  vault-subdirectory:
    description: 'Sub-directory within the Obsidian vault to export.'
    required: true
    default: '/'
outputs:
  export-branch:
    description: 'Branch with exported obsidian vault'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.vault-location }}
    - ${{ inputs.vault-subdirectory }}